server:
  port: 8080

#配置数据源
#spring:
#  #配置数据源
#  datasource:
#    #MySql配置
#    url: jdbc:mysql://119.91.65.129:3306/yezhike_cn?useUnicode=true&characterEncoding=utf8&useSSL=false&serverTimezone=Asia/Shanghai&tinyInt1isBit=false
#    username: root
#    password: Ye_84802038
#    driver-class-name: com.mysql.cj.jdbc.Driver
